This is makeindex, version 2.15 [TeX Live 2017] (kpathsea + Thai support).
Scanning style file /Users/carthach/Desktop/tmp/phd_thesis/PhDThesis/.texpadtmp/Carthach_PhDThesis.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file /Users/carthach/Desktop/tmp/phd_thesis/PhDThesis/.texpadtmp/Carthach_PhDThesis.acn....done (413 entries accepted, 0 rejected).
Sorting entries......done (3899 comparisons).
Generating output file /Users/carthach/Desktop/tmp/phd_thesis/PhDThesis/.texpadtmp/Carthach_PhDThesis.acr....done (299 lines written, 0 warnings).
Output written in /Users/carthach/Desktop/tmp/phd_thesis/PhDThesis/.texpadtmp/Carthach_PhDThesis.acr.
Transcript written in /Users/carthach/Desktop/tmp/phd_thesis/PhDThesis/.texpadtmp/Carthach_PhDThesis.alg.
